#specifies the base image for the Docker image,base image refers to the starting point for creating a Docker container
FROM node:alpine 
#copies the contents of the current directory
COPY . /partb   
#execute the "index.js" script located in the "partb" directory within the container
CMD node /partb/index.js   